### PR TITLE
bump to electron 20

### PR DESCRIPTION
**Pull request by jackkav**
required to update insomnia to electron 20

### CODE REVIEW

**Comment by DMarby** [comment]
Looks like the electron builds are failing, I think we might need to update node-gyp/node-pre-gyp and/or nan?

**Comment by jackkav** [comment]
Lets hope its this:
> /home/runner/.cache/node-gyp/20.0.0/include/node/node.h:27:2: error: #error "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=8.4.0) if you're building modules directly."

**Comment by DMarby** [comment]
Errors from the Ubuntu builds seems related to this: https://github.com/electron/electron/issues/35193

> Lets hope its this:
> 
> > /home/runner/.cache/node-gyp/20.0.0/include/node/node.h:27:2: error: #error "It looks like you are building this native module without using the right config.gypi.  This normally means that you need to update electron-rebuild (>=3.2.8) or node-gyp (>=8.4.0) if you're building modules directly."

**Comment by jackkav** [comment]
relevant error, issue and pr
> no known conversion for argument 7 from ‘Nan::imp::Sig {aka int}’ to ‘v8::SideEffectType’
https://github.com/electron/electron/issues/35193
https://github.com/nodejs/nan/pull/943

**Pull request closed without merging**
